[local]
AETitle = ""
IP = ""
Port = 11112

[rvs]
AETitle = ""
IP = ""
Port = 11112

[mim_server]
AETitle = ""
IP = ""
Port = 11112

[mim_server_qr]
AETitle = ""
IP = ""
Port = 11112

[aria]
AETitle = ""
IP = ""
Port = 11112

[mosaiq]
AETitle = ""
IP = ""
Port = 11112

[orthanc]
AETitle = ""
IP = ""
Port = 11112
