[local]
AETitle = ""
IP = ""
Port = "ENTER PORT AS INT"

[rvs]
AETitle = ""
IP = ""
Port = "ENTER PORT AS INT"

[mim_server]
AETitle = ""
IP = ""
Port = "ENTER PORT AS INT"

[mim_server_qr]
AETitle = ""
IP = ""
Port = "ENTER PORT AS INT"

[aria]
AETitle = ""
IP = ""
Port = "ENTER PORT AS INT"

[mosaiq]
AETitle = ""
IP = ""
Port = "ENTER PORT AS INT"

[orthanc]
AETitle = ""
IP = ""
Port = "ENTER PORT AS INT"
