[local]
AETitle = ""
IP = ""
Port = 11112

[rvs]
AETitle = ""
IP = ""
Port = 11112

[mim_server]
AETitle = ""
IP = ""
Port = 11112

[mim_server_qr]
AETitle = ""
IP = ""
Port = 11112

[aria]
AETitle = ""
IP = ""
Port = 11112

[mosaiq]
AETitle = ""
IP = ""
Port = 11112

# Main Orthanc server for backup (C-MOVE destination, C-FIND/C-GET target)
[orthanc]
AETitle = "ORTHANC_BACKUP"
IP = "127.0.0.1" # User should change this to the actual IP
Port = 104       # User should change this to the actual port, 104 is common for DICOM

# Staging SCP for Mosaiq-generated instances before C-MOVE to main backup
[staging_scp_for_mosaiq]
AETitle = "MOSAIQ_STAGING_SCP"
IP = "127.0.0.1" # User should change this, could be a local SCP
Port = 11113     # User should change this to a free port
